# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Stride Docs (Fast Track) for Azure Web App Staging

on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'README.md'
  #     - 'Stride.Docs.sln'
  #     - 'BuildDocs.ps1'
  #     - 'wiki/**'
  #     - .gitignore
  #     - '.github/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: windows-2022
    environment:
      name: 'Production'

    steps:
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Checkout Stride Docs
      uses: actions/checkout@v3
      with:
        path: stride-docs
        lfs: true

    - name: Checkout Stride (note the LFS)
      uses: actions/checkout@v3
      with:
        repository: stride3d/stride
        token: ${{ secrets.GITHUB_TOKEN }}
        path: stride
        lfs: true

    - name: Install DocFX
      # This installs the latest version of DocFX and may introduce breaking changes.
      # run: dotnet tool update -g docfx
      # This installs a specific, tested version of DocFX.
      run: dotnet tool update -g docfx --version 2.70.1

    - name: Build documentation
      run: ./build-all.bat
      working-directory: stride-docs

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
          app-name: 'stride-doc'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_32FCD402B970463A9143B24C9B225749 }}
          package: ./stride-docs/_site
